services:
  manyfold-processor:
    build: .
    image: manyfold-processor:latest
    container_name: manyfold-processor
    restart: unless-stopped
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - STAGING_DIR=/staging
      - OUTPUT_DIR=/output
      - AUTO_OFF_WHEN_DONE=true
      - AUTO_PROCESS=false
    volumes:
      - ./playground/input:/input
      - ./playground/output:/output
      - ./playground/staging:/staging
      - ./playground/config:/config
